---
 # Exercise for setting up a web server in an EC2 instance
- name: Exercise for setting up a web server in an EC2 instance
   # hosts: ubuntu
   # Use the public IP if the VM is already created
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for:
         delay: 600 

  roles:
  - setup