AWSTemplateFormatVersion: 2010-09-09
Description: Continous delivery using circle CI, creating an AWS instance

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22 and port 3030
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity-pem
      ImageId: ami-068663a3c619dd892
      InstanceType: t2.micro
      Tags:
        - Key: "cd-deployment"
          Value: !Sub ansible-${ID}