AWSTemplateFormatVersion: 2010-09-09
Description: Continous delivery using circle CI, creating an AWS instance
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity-pem
      ImageId: 'ami-08c40ec9ead489470' 
      InstanceType: t2.micro
      Tags:
        - Key: "cd-deployment"
          Value: "ansible"
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 